### ISSUE TITLE
Coriger l'ortograf + traduire

### ISSUE THREAD

**Issue by NeKroFR** [aniito/skid_tool#2]
Changer la description de "scripte simple en python pour brute-force (skid) le ctf : https://ctf-1-ymortail.netlify.app/? || normalement ont peut y arriver plus simplement"

à   "Simple python script to skid bruteforce  the ctf: https://ctf-1-ymortail.netlify.app/? ||  but their is easyer ways "

**Comment by aniito** [comment]
aucune faute n'a été recensée dans mon script. seulement une traduction à été ajoutée ne dites pas de balivernes ! "Coriger l'ortograf + traduire"
